name: EnvTBsom
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - sklearn
  - scipy
  - time
  - json
  - sys
  - csv
  - os
  - pip:
    - clustergrammer_widget
  - jupyter nbextension enable --py --sys-prefix widgetsnbextension
  - jupyter nbextension enable --py --sys-prefix clustergrammer_widget
