name: example-environment
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - sklearn
  - scipy
  - time
  - json
  - sys
  - csv
  - os
pip:
  - clustergrammer_widget
